services:
  mc:
    image: mirth311
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://postgres:5432/postgres
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - VMOPTIONS=-Xmx512m
    volumes:
      - ./data/volumes/appdata:/opt/connect/appdata
      - ./data/volumes/hl7:/opt/hl7
    ports:
      - 8445:8445/tcp
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    ports:
      - "5432:5432"